---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
  - Пользователь должен иметь возможность переключить язык интерфейса.
  - Сайт должен иметь локализацию (перевод) на русский и английский языки.
  - Интернет-магазин представляет собой SPA-приложение, которое не перезагружает страницу.
  - В каталоге товаров работает пагинация, в том числе при фильтрации товаров.
  - На странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без нее. 
  - Пользователь может добавить товар в корзину и продолжать выбирать товары в каталоге.
  - На странице корзины пользователь может удалить товар из корзины.
  - Пользователь может оформить заказ с переходом на страницу оплаты.
  - Корзина хранится в сессии браузера.
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь адаптивную верстку для удобства на мобильных устройствах.
  - Сайт нужно протестировать на совместимость с последними версиями браузеров.
  - Важно, чтобы сайт мог обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
  - Сайт должен иметь локализацию (перевод) на русский и английский языки.
implicit:
  - Сайт должен работать на протоколе https.